api/urls.py
from django.urls import path
from .views import add_description

app_name = "api"

urlpatterns = [
	path('add_description/', add_description, name='add-description'),
]

image_recognition/urls.py
from django.urls import path
from . import views
from .views import (
	ImageListView,
	ImageDetailView, 
	ImageCreateView, 
	ImageDeleteView,
	UserImageListView)

urlpatterns = [
	path('', ImageListView.as_view(), name='image_recognition-home'),
	path('user-images/', UserImageListView.as_view(), name='user-images'),
	path('image/<int:pk>/', ImageDetailView.as_view(), name='image-detail'),
	path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='image-delete'),
	path('image/new/', ImageCreateView.as_view(), name='image-create'),
	path('about/', views.about, name='image_recognition-about'),
]

image_recognition_webapp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('register/', user_views.register, name='register'),
	path('profile/', user_views.profile, name='profile'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('', include('image_recognition.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

image_recognition/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Image(models.Model):
	user_description = models.TextField()
	model_description = models.TextField(blank=True, null=True)
	description_ready = models.BooleanField(default=False)
	original_image = models.ImageField(default=None, upload_to='original_images')
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.original_image)

	def get_absolute_url(self):
		return reverse('image-detail', kwargs={'pk': self.pk})

class ImageAttentionDescription(models.Model):
	image = models.ForeignKey(Image, on_delete=models.CASCADE)
	attention_image = models.ImageField(default=None, upload_to='attention_images')
	attention_word = models.TextField()

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = [
			'username', 
			'email',
			'password1',
			'password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = [
			'username', 
			'email']


class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['image']

api/views.py
from django.shortcuts import render
from image_recognition.models import ImageAttentionDescription, Image
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponseNotFound
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.db.utils import IntegrityError


@csrf_exempt
def add_description(request):
	if request.method == "POST":
		data = request.POST
		data = dict(data)
		secret_key = str(data.get('secret_key', '')[0])
		image_id = int(data['image_id'][0])

		
		# if str(secret_key) == os.environ.get('AWS_SECRET_ACCESS_KEY'):
		if str(secret_key) == "87654321":
			try:
				full_description = ''
				for index in range(0, len(data["text"])):
					image_name = str(data["pictures"][index])
					described_word = str(data["text"][index])
					full_description = full_description + described_word + ' '
					ImageAttentionDescription.objects.create(image_id=image_id, attention_image=image_name, attention_word=described_word)
				image = Image.objects.filter(id=image_id).first()
				image.model_description = full_description
				image.description_ready = True
				image.save()
				return JsonResponse({'Success': 'True'})
			except KeyError as e:
				return JsonResponse({'error': str(e)})
	else:
		return JsonResponse({'error': f"Request method not supported: {request.method}"})

image_recognition/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
	ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Image


def home(request):
	context = {
		'images': Image.objects.all()
	}
	return render(request, 'blog/home.html', context)

class ImageListView(ListView):
	model = Image
	template_name = 'image_recognition/home.html'
	context_object_name = 'images'
	ordering = ['-date_posted']
	paginate_by = 5


class UserImageListView(LoginRequiredMixin, ListView):
	model = Image
	template_name = 'image_recognition/user_images.html'
	context_object_name = 'images'
	ordering = ['-date_posted']
	paginate_by = 5

	def get_queryset(self):
		user = self.request.user
		return Image.objects.filter(author=user).order_by('-date_posted')


class ImageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = Image

	def test_func(self):
		image = self.get_object()
		if self.request.user == image.author:
			return True
		else:
			return False

class ImageCreateView(LoginRequiredMixin, CreateView):
	model = Image
	fields = ['user_description', 'original_image']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class ImageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Image
	success_url = '/'

	def test_func(self):
		image = self.get_object()
		if self.request.user == image.author:
			return True
		else:
			return False


def about(request):
	context = {
		'title': 'About Section'
	}
	return render(request, 'image_recognition/about.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Your account has been created, {username}! You can now log in.')
			return redirect('login')
	else:
		form = UserRegisterForm()


	return render(request,
		'users/register.html',
		{'form': form})

@login_required
def profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f'Your account has been updated.')
			return redirect('profile')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)
	context = {
		'u_form': u_form,
		'p_form': p_form,	
	}
	return render(request, 'users/profile.html', context)

image_recognition/templates/image_recognition/about.html
{% extends "image_recognition/base.html" %}
{% block content %}
<h1>About</h1>
<hr>
<p>The <b>Image Description App</b> is a project for Cloud Technologies class at Warsaw University of Technology.</p>

<p>After creating a account user is able to upload his picture and recieve AI generated description of
content of the image.</p>
{% endblock content %}

image_recognition/templates/image_recognition/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
    	<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static 'image_recognition/main.css' %}">

		<!-- Title -->
		<title>Image Decription App</title>


	</head>
	<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
					<a class="navbar-brand mr-4" href="{% url 'image_recognition-home' %}">Image Description App</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarToggle">
						<div class="navbar-nav mr-auto">
							<a class="nav-item nav-link" href="{% url 'image_recognition-about' %}">About</a>
						</div>
		        <!-- Navbar Right Side -->
						<div class="navbar-nav">
							{% if user.is_authenticated %}
								<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
							{% else %}
								<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
							{% endif %}
						</div>
					</div>
				</div>
			</nav>
		</header>
		
		<main role="main" class="container">
		  <div class="row">
		    <div class="col-md-8">
		    	{% if messages %}
		    		{% for message in messages %}
		    			<div class="alert alert-{{ message.tags }}">
		    				{{ message }}
		    			</div>
		    		{% endfor %}
		    	{% endif %}

				{% block content %}
				{% endblock %}
		    </div>
		    <div class="col-md-4">
		      	<div class="content-section">
		      		{% if user.is_authenticated %}
		        	<h5>Logged in as {{ user.username }}</h5>
				        <p class='text-dark'>Go to:
				          <ul class="list-group">
				          	<li class="list-group-item list-group-item-light"><a href="{% url 'image-create' %}">Upload new image</a></li>
				          	<li class="list-group-item list-group-item-light"><a href="{% url 'user-images' %}">Show my images</a></li>
				          	<li class="list-group-item list-group-item-light"><a href="{% url 'profile' %}">My profile</a></li>
				          </ul>
		        		</p>
		        	{% else %}
						<h4>To upload a picture, you have to be logged in</h4>
						<p class='text-dark'>If you want to create new account, click the register button below. 
				          <ul class="list-group">
				            <li class="list-group-item list-group-item-light"><a href="{% url 'register' %}">Register</a></li>
				          </ul>
		        		</p>
		        	{% endif %}
		      		</div>
		    	</div>
		  	</div>
		</main>
		
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

image_recognition/templates/image_recognition/home.html
{% extends "image_recognition/base.html" %}
{% block content %}
<h1>Welcome to the Image Description App!</h1>
<hr>

{% if user.is_authenticated %}
	<p>To upload a image and get its description, click on <b>Upload new image</b> button on the right panel. 
		To explore your uploaded images and their descriptions, click on the <b>Show my images</b> button on the right panel.</p>
{% else %}
	<p>After creating a account, you will be able to upload a picture and recieve AI generated description of
content of the image. To create a account, click on the <b>Register</b> button on the right panel. </p>
{% endif %}

{% endblock content %}

image_recognition/templates/image_recognition/image_confirm_delete.html
{% extends "image_recognition/base.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Delete image
				</legend>
				<h2>Are you sure you want to delete this picture?</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">	
					Yes, Delete
				</button>
				<a class="btn btn-outline-secondary" href="{% url 'image-detail' object.id %}">	
					No, Cancel
				</a>
			</div>
		</form>
	</div>
{% endblock content %}

image_recognition/templates/image_recognition/image_detail.html
{% extends "image_recognition/base.html" %}
{% block content %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <h1>Full results</h1>
		      <small class="text-muted">Image uploaded by <a class="mr-2" href="{% url 'profile' %}">{{ object.author }}</a>at {{ object.date_posted|date:"Y F d, G:i" }} UTC</small>
		    </div>
		    <img class="img-fluid" src="{{ object.original_image.url }}">
		    <hr>
		    <h3>Image description</h3>
		    <p><b>User description: </b> {{ object.user_description }}</p>
		    <p><b>Model description: </b>
		    {% if object.description_ready == True %}
		    	{{ object.model_description }}
		    {% else %}
		    	<em>Description not ready. Refresh this page.</em> <a class="article-title btn btn-info" href="{% url 'image-detail' object.id %}">Refresh</a>
		    {% endif %}
			</p>
		    <hr>
		  	<h3>Model attention</h3>
		  	<div class="text-center">
		  	{% for attribute in object.imageattentiondescription_set.all %}
		  		<img class="img-fluid" src="{{ attribute.attention_image.url }}">
		  		<h4>{{ attribute.attention_word }}</h4>
		  	{% endfor %}
		  </div>
		  </div>
		  
		</article>
{% endblock content %}

image_recognition/templates/image_recognition/image_form.html
{% extends "image_recognition/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST", enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Upload new image
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">	
					Upload picture
				</button>
			</div>
		</form>
	</div>
{% endblock content %}

image_recognition/templates/image_recognition/user_images.html
{% extends "image_recognition/base.html" %}
{% block content %}
<h1 class="mb-3">Images uploaded ({{ page_obj.paginator.count }})</h1>
	{% for image in images %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      
		      <small class="text-muted">Image uploaded by <a class="mr-2" href="{% url 'profile' %}">{{ image.author }}</a>at {{ image.date_posted|date:"Y F d, G:i" }} UTC</small>
		    </div>
		    <h2><a class="article-title btn btn-info" href="{% url 'image-detail' image.id %}" style="color:white">Full results</a></h2>
		    <p><b>User description: </b> {{ image.user_description }}</p>
		    <p><b>Model description: </b>
		    {% if image.description_ready == True %}
		    	{{ image.model_description }}
		    {% else %}
		    	Description not ready. Please try refreshing this page in few seconds. 
		    {% endif %}
			</p>
		    <img class="img-fluid" src="{{ image.original_image.url }}">
		  </div>
		</article>
	{% endfor %}
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
				<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		{% endif %}

	{% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends "image_recognition/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Log In
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">	
					Login
				</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				You don't have an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a> 
			</small>
		</div>
	</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "image_recognition/base.html" %}
{% block content %}
	<h2>You have been logged out</h2>
	<div class="border-top pt-3">
		<small class="text-muted">
			<a href="{% url 'login' %}">Log in again</a> 
		</small>
	</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "image_recognition/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
			<div class="media-body">
				<h2 class="account-heading">{{ user.username }}</h2>
				<p class="text-secondary">{{ user.email }}</p>
			</div>
		</div>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Update your profile:
				</legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">	
					Update
				</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/register.html
{% extends "image_recognition/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Join Today!
				</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">	
					Sign Up
				</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Already have an account? <a class="ml-2" href="{% url 'register' %}">Sign In</a> 
			</small>
		</div>
	</div>
{% endblock content %}